name: duro by team kapppa
run-name: ${{ github.actor }} 
on: 
  push:
    branches:
      - 'dev'

jobs:
  dockerize_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Build and push doorman
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./backend.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/duro-doorman:latest

      -
        name: Build and push butler
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./frontend.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/duro-butler:latest

      -
        name: Build and push tray
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./cron.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/duro-tray:latest
